### ISSUE TITLE
If 'evaled' throws Parse error

### ISSUE THREAD

**Issue by mracos** [haskellcamargo/php-code-without-any-workaround#1]
Actually, if I try to eval the contents of [index,php](https://raw.githubusercontent.com/haskellcamargo/php-code-without-any-workaround/master/index.php), I get the following error:

`PHP Parse error:  syntax error, unexpected '<', expecting end of file in /home/marcos/bug-free-code.php(4) : eval()'d code on line 1` :thinking: :thinking:

I expected bug free code but instead I get this!!!! :rage: :rage:

**Comment by gabrielpaivadev** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK[...]

**Comment by ttibau** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
